services:
  tensorboard:
    build: tensorboard_compose
    container_name: tensorboard
    image: ${TENSORBOARD_IMAGE_NAME}
    ports:
    - 6006:6006
    volumes:
      - ./tb_folder:/tb_folder
  server1:
    build: nvflare_compose
    command:
    - ${PYTHON_EXECUTABLE}
    - -u
    - -m
    - nvflare.private.fed.app.server.server_train
    - -m
    - ${WORKSPACE}
    - -s
    - fed_server.json
    - --set
    - secure_train=true
    - config_folder=config
    - org=nvidia
    container_name: server1
    image: ${IMAGE_NAME}
    ports:
    - 8002:8002
    - 8003:8003
    volumes:
    - ./server1:${WORKSPACE}
    - ./tb_folder:/tb_folder
    - nvflare_svc_persist:/tmp/nvflare/
  site-1:
    build: nvflare_compose
    command:
    - ${PYTHON_EXECUTABLE}
    - -u
    - -m
    - nvflare.private.fed.app.client.client_train
    - -m
    - ${WORKSPACE}
    - -s
    - fed_client.json
    - --set
    - secure_train=true
    - uid=site-1
    - org=nvidia
    - config_folder=config
    container_name: site-1
    image: ${IMAGE_NAME}
    volumes:
    - ./data:/data
    - ./site-1:${WORKSPACE}
  site-2:
    build: nvflare_compose
    command:
    - ${PYTHON_EXECUTABLE}
    - -u
    - -m
    - nvflare.private.fed.app.client.client_train
    - -m
    - ${WORKSPACE}
    - -s
    - fed_client.json
    - --set
    - secure_train=true
    - uid=site-2
    - org=nvidia
    - config_folder=config
    container_name: site-2
    image: ${IMAGE_NAME}
    volumes:
    - ./data:/data
    - ./site-2:${WORKSPACE}
volumes:
  nvflare_svc_persist: null
